import Head from "next/head";
import styles from "./layout.module.css";


const Layout = ({ children }) => {
    return(
        <>
            <Head>
                <title>Demo Marketplace</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {children}
            </main>
        </>
    )
}

export default Layout;