import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Demo Marketplace
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="http://http://ec2-3-26-19-82.ap-southeast-2.compute.amazonaws.com/consumer"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Consumer →</h3>
              <div className={styles.cardText}>
                Post a job so makers can view and make you an offer.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="http://http://ec2-3-26-19-82.ap-southeast-2.compute.amazonaws.com/maker"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Maker →</h3>
              <div className={styles.cardText}>
                Search all available jobs and find a great match to quote your services on.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
